In [1]:
import numpy as np

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [3]:
vector_uniform = np.random.uniform(0, 1, 10)
print("Vector (uniform):", vector_uniform)
print("Vector shape:", vector_uniform.shape)

vector_rand = np.random.rand(10)
print("\nVector (rand):", vector_rand)
print("Vector shape:", vector_rand.shape)

matrix = np.array([
    [11, 14, 17],
    [20, 23, 26],
    [29, 32, 35]
])
print("\nMatrix:\n", matrix)
print("Matrix shape:", matrix.shape)

matrix_reshape = np.array([11, 14, 17, 20, 23, 26, 29, 32, 35]).reshape(3, 3)
print("\nMatrix (reshape):\n", matrix)
print("Matrix shape (reshape):", matrix.shape)

Vector (uniform): [0.98869732 0.42780066 0.31996823 0.51951102 0.81231717 0.85939801
 0.56798772 0.179848   0.64790741 0.39448457]
Vector shape: (10,)

Vector (rand): [0.14780831 0.92028094 0.56074088 0.21180977 0.67840865 0.80084609
 0.54479086 0.65665992 0.96525993 0.02667498]
Vector shape: (10,)

Matrix:
 [[11 14 17]
 [20 23 26]
 [29 32 35]]
Matrix shape: (3, 3)

Matrix (reshape):
 [[11 14 17]
 [20 23 26]
 [29 32 35]]
Matrix shape (reshape): (3, 3)


### Summary

Two random vectors of size 10 were generated:

- The first one was generated using `np.random.uniform(0, 1, 10)` which samples random real values uniformly distributed between 0 and 1.
- The second one was generated using `np.random.rand(10)` which produces similar uniformly distributed random values between 0 and 1.

A 3x3 matrix was also created in two ways:

- Directly using `numpy.array` with predefined integer values.
- Using a one-dimensional list of values reshaped into a 3x3 matrix with `reshape(3, 3)`.

In both cases, the matrix contains the same elements and has the expected shape of `(3, 3)`.



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [4]:
vector_added = np.round(vector_rand + 10, 2)
print("Vector after adding 10 and rounding:", vector_added)

Vector after adding 10 and rounding: [10.15 10.92 10.56 10.21 10.68 10.8  10.54 10.66 10.97 10.03]


In [5]:
matrix_multiplied = matrix * 2
print("\nMatrix after multiplying by 2:\n", matrix_multiplied)


Matrix after multiplying by 2:
 [[22 28 34]
 [40 46 52]
 [58 64 70]]


In [6]:
vector_squared = vector_rand ** 2
print("\nVector squared:", vector_squared)


Vector squared: [2.18472959e-02 8.46917001e-01 3.14430334e-01 4.48633786e-02
 4.60238296e-01 6.41354459e-01 2.96797081e-01 4.31202257e-01
 9.31726729e-01 7.11554435e-04]


### Summary

Several operations were performed using NumPy without explicit loops:

- Added 10 to each element of the vector and rounded the result to 2 decimal places using `np.round()`.
- Multiplied each element of the matrix by 2 using vectorized operations.
- Created a new vector containing the square of each element of the original vector using element-wise exponentiation..


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [7]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [15]:
result_matrix = np.dot(B, A)
print("Result matrix (B dot A) with shape 2x2:\n", result_matrix)
print("Shape:", result_matrix.shape)

Result matrix (B dot A) with shape 2x2:
 [[0.7281 0.5202]
 [0.2034 0.2846]]
Shape: (2, 2)


In [13]:
result_vector = np.dot(result_matrix, C)
print("\nResult of result_matrix dot C:\n", result_vector)
print("Shape:", result_vector.shape)


Result of result_matrix dot C:
 [[0.5202]
 [0.2846]]
Shape: (2, 1)


In [14]:
result_final = np.dot(result_matrix, D)
print("\nResult of result_matrix dot D:\n", result_final)
print("Shape:", result_final.shape)


Result of result_matrix dot D:
 [[0.5202 0.7281]
 [0.2846 0.2034]]
Shape: (2, 2)


### Summary

Matrix and vector multiplications were performed using NumPy's `dot` function:

- First, matrices `B (2x3)` and `A (3x2)` were multiplied to obtain `result_matrix` of shape `(2x2)`.
- Next, `result_matrix (2x2)` was multiplied by vector `C (2x1)` to produce a result of shape `(2x1)`.
- Finally, `result_matrix (2x2)` was multiplied by matrix `D (2x2)` to produce a final result of shape `(2x2)`.



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [16]:
result_matrix_transposed = result_matrix.T
print("Transposed result_matrix:\n", result_matrix_transposed)
print("Shape:", result_matrix_transposed.shape)

Transposed result_matrix:
 [[0.7281 0.2034]
 [0.5202 0.2846]]
Shape: (2, 2)


In [18]:
vector_transposed = vector_rand.T
print("\nTransposed vector:\n", vector_transposed)
print("Shape:", vector_transposed.shape)


Transposed vector:
 [0.14780831 0.92028094 0.56074088 0.21180977 0.67840865 0.80084609
 0.54479086 0.65665992 0.96525993 0.02667498]
Shape: (10,)


In [19]:
print("\nOriginal vector shape:", vector_rand.shape)


Original vector shape: (10,)


In [20]:
column_vector = np.expand_dims(vector_rand, axis=1)
print("\nColumn vector (expand_dims):\n", column_vector)
print("Shape:", column_vector.shape)


Column vector (expand_dims):
 [[0.14780831]
 [0.92028094]
 [0.56074088]
 [0.21180977]
 [0.67840865]
 [0.80084609]
 [0.54479086]
 [0.65665992]
 [0.96525993]
 [0.02667498]]
Shape: (10, 1)


In [21]:
column_vector_transposed = column_vector.T
print("\nTransposed column vector:\n", column_vector_transposed)
print("Shape:", column_vector_transposed.shape)


Transposed column vector:
 [[0.14780831 0.92028094 0.56074088 0.21180977 0.67840865 0.80084609
  0.54479086 0.65665992 0.96525993 0.02667498]]
Shape: (1, 10)


### Summary

Several transpose operations were performed:

- `result_matrix` was successfully transposed, changing its shape from `(2x2)` to `(2x2)` (square matrix, shape remains same).
- Transposing the 1D `vector` had no effect on its shape, which remained `(10,)`, because transposing has no effect on 1D arrays in NumPy.
- `expand_dims(vector, axis=1)` was used to convert the 1D vector into a column vector with shape `(10, 1)`.
- Transposing the `column_vector` resulted in a row vector with shape `(1, 10)`.
